apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.app_name}}
  description: Valkey db cluster named ${{values.app_name}}
  annotations:
    github.com/project-slug: test-backstage6/${{values.app_name}}
    backstage.io/techdocs-ref: dir:.
  links:
    - url: https://dashboard.example.com
      title: Grafana dashboard for ${{values.app_name}}
      icon: dashboard
spec:
  type: service
  owner: development
  lifecycle: experimental
