apiVersion: saas.wp.pl/v1alpha1
kind: WpValkey
metadata:
  annotations:
    helm.sdk.operatorframework.io/reconcile-period: 1h
  labels:
    argocd.argoproj.io/instance: ${{values.app_name}}
  name: ${{values.app_name}}
  namespace: dsa-test
spec:
  maxmemoryPolicy: volatile-ttl
  size: ${{values.app_size}}