apiVersion: saas.wp.pl/v1alpha1
kind: WpValkey
metadata:
  annotations:
    helm.sdk.operatorframework.io/reconcile-period: 1h
  labels:
    argocd.argoproj.io/instance: "${{values.app_name}}"
  name: "${{values.app_name}}"
  namespace: wpsaas-${{values.app_user}}
spec:
  maxmemoryPolicy: ${{values.app_policy}}
  size: ${{values.app_size}}