apiVersion: saas.wp.pl/v1alpha1
kind: WpValkey
metadata:
  annotations:
    helm.sdk.operatorframework.io/reconcile-period: 1h
  labels:
    argocd.argoproj.io/instance: ${{parameters.app_name}}
  name: ${{parameters.app_name}}
  namespace: dsa-test
spec:
  maxmemoryPolicy: volatile-ttl
  size: ${{parameters.app_size}}