
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{values.app_name}}
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: wpsaas-${{values.app_user}}
  sources:
    - repoURL: https://nexus-rm.grupawp.pl/repository/saas-valkey-sentinel/
      chart: saas-valkey-sentinel
      targetRevision: 1.0.1
      helm:
        values: |
          maxmemoryPolicy: ${{values.app_policy}}
          size: ${{values.app_size}}
  destination:
    server: https://kubernetes.default.svc
    namespace: wpsaas-${{values.app_user}}
  syncPolicy:
    automated:
      selfHeal: true