apiVersion: saas.wp.pl/v1alpha1
kind: WpValkey
metadata:
  annotations:
    helm.sdk.operatorframework.io/reconcile-period: 1h
  labels:
    argocd.argoproj.io/instance: ${{ user.entity.metadata.name }}-${{values.app_name}}
  name: ${{ user.entity.metadata.name }}-${{values.app_name}}
  namespace: dsa-test
spec:
  maxmemoryPolicy: ${{values.app_policy}}
  size: ${{values.app_size}}