apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: valkey-template
  title: Valkey template
  description: Provisions Valkey db cluster
spec:
  owner: development
  type: service

  parameters:
    - title: Fill in some steps
      required:
        - component_id
        - environment
      properties:
        component_id:
          title: Component name
          type: string
          description: Provide a component (microservice) name
          pattern: '^([a-zA-Z][a-zA-Z0-9]*)(-[a-zA-Z0-9]+)*$'
        environment:
          title: Size
          type: string
          description: The environment where this component will be deployed
          enum:
            - s1
            - m1
            - l1

  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./template
        values:
          app_name: ${{parameters.component_id}}
          app_size: ${{parameters.environment}}

    - id: publish
      name: Publish
      action: publish:github:pull-request
      input:
        allowedHosts:
          - github.com
        description: ${{ parameters.component_id }} configuration
        repoUrl: github.com?owner=test-backstage6&repo=saas
        branchName: add-${{ parameters.component_id }}
        title: Add ${{ parameters.component_id }} configuration
        targetPath: ./${{parameters.component_id}}
        sourcePath: ./
        automerge: true

  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
      - title: Pull Request
        url: ${{ steps['publish'].output.pullRequestUrl }}
      - title: Register after merge
        url: https://github.com/test-backstage6/saas/blob/main/${{parameters.component_id}}/catalog-info.yaml
