apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: valkey-sentinel-template
  title: Valkey sentinel template
  description: Provisions Valkey sentinel cluster
spec:
  owner: development
  type: service

  parameters:
    - title: Fill in some steps
      required:
        - component_id
        - environment
      properties:
        component_id:
          title: Valkey cluster name.
          type: string
          description: Provide a valkey cluster name. Prefix vk- will be added automatically
          pattern: '^([a-zA-Z][a-zA-Z0-9]*)(-[a-zA-Z0-9]+)*$'
        environment:
          title: Size
          type: string
          description: Size of valkey cluster
          enum:
            - s1
            - m1
            - l1
        policy:
          title: Eviction policy
          type: string
          description: Valkey keys eviction policy
          enum:
            - volatile-ttl
            - allkeys-lru
            - volatile-lru
            - allkeys-random
            - volatile-random
            - volatile-lfu
            - allkeys-lfu
            - noeviction

  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./template
        values:
          app_name: vk-${{parameters.component_id}}
          app_size: ${{parameters.environment}}
          app_policy: ${{parameters.policy}}
          app_user: ${{ user.entity.metadata.name }}

    - id: publish
      name: Publish
      action: publish:github:pull-request
      input:
        allowedHosts:
          - github.com
        description: vk-${{parameters.component_id}} configuration
        repoUrl: github.com?owner=test-backstage6&repo=saas
        branchName: add-vk-${{parameters.component_id}}
        title: Add vk-${{parameters.component_id}} configuration
        targetPath: ./vk-${{parameters.component_id}}
        sourcePath: ./
        automerge: true
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - id: wait
      name: Waiting for merge
      action: debug:wait
      input:
        seconds: 20

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: https://github.com/test-backstage6/saas/blob/main/
        catalogInfoPath: "/vk-${{parameters.component_id}}/catalog-info.yaml"
